name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.x'
      - name: Run checks
        run: ./scripts/check.sh
      - name: Lint shell scripts
        run: ./scripts/shellcheck.sh
